name: Terraform Base Infra CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    permissions:
      contents: read
      pull-requests: write

    name: "Base Infra"
    uses: ./.github/workflows/tf-change-management.yaml
    with:
      working_directory: "base-infra"
    secrets:
      tfc_token: ${{ secrets.TFC_API_TOKEN }}
  
  
