name: Terraform Base Infra CI

on:
  push:
  pull_request:
    branches:
      - main
      - features/**
    paths:
      - base-infra/**

jobs:
  terraform:
    name: "Terraform"
    uses: ./.github/workflows/tf-change-management.yaml
    with:
      env: "dev"
      bucket_name: ${{ vars.BUCKET_NAME }}
      bucket_key: ${{ vars.BUCKET_KEY }}
      lock_dynamodb_name: ${{ vars.LOCK_DYNAMODB_NAME }}
      region: ${{ vars.REGION }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
