name: CI Workflow

on:
  pull_request:
    branches:
      - dev
      - main
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    permissions:
      contents: read
      pull-requests: write

    name: "CI"
    uses: ./.github/workflows/tf-change-management.yaml
    with:
      working_directory: "base-infra"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      bucket_name: ${{ secrets.BUCKET_NAME }}
      bucket_key: ${{ secrets.INFA_BUCKET_KEY }}
      lock_dynamodb_name: ${{ secrets.LOCK_DYNAMODB_NAME }}
