name: Terraform CI

on:
  push:
    branches:
      - main
      - features/**
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test_and_validate:
    uses: ./.github/workflows/tf_change_management.yaml
