name: Deploy Workflow

on:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write

    name: "CD"
    uses: ./.github/workflows/tf-apply.yaml
    with:
      working_directory: "base-infra"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      bucket_name: ${{ secrets.BUCKET_NAME }}
      bucket_key: ${{ secrets.INFA_BUCKET_KEY }}
      lock_dynamodb_name: ${{ secrets.LOCK_DYNAMODB_NAME }}
