name: Terraform Destroy Workflow

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

    secrets:
      aws_access_key_id:
        required: true
      aws_secret_key_id:
        required: true
      bucket_name:
        required: true
      bucket_key:
        required: true
      lock_dynamodb_name:
        required: true
      aws_region:
        required: true


jobs:
  terraform:
    name: "TF Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{inputs.working_directory}}

    steps:
      - name: Checkout the code to the runner
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_key_id }}
          aws-region: ${{ secrets.aws_region }}

      - name: Terraform Setup
        uses: ./.github/actions/setup-terraform
        id: setup
        with:
          working_directory: ${{ inputs.working_directory }}
          bucket_name: ${{ secrets.bucket_name }}
          bucket_key: ${{ secrets.bucket_key }}
          lock_dynamodb_name: ${{ secrets.lock_dynamodb_name }}
          aws_region: ${{ secrets.aws_region }}

      - name: Terraform Destroy
        id: apply
        run: >
         terraform destroy --auto-approve